name: gapsec
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #SPLASH SCREEN
  animated_splash_screen: ^1.3.0
  #Page Trans
  page_transition: ^2.1.0
  #ANIMATED TEXT
  animated_text_kit: ^4.2.2
  #MOBX
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  #Video Player
  video_player: ^2.9.1
  #Audio Player
  audioplayers: ^6.0.0
  #localization
  easy_localization: ^3.0.7
  #Animated Tabs
  tab_container: ^3.5.3
  #Carousel Slider
  carousel_slider: ^5.0.0
  #Smooth Page Indicator
  smooth_page_indicator: ^1.2.0+3
  #Logger(print)
  logger: ^2.4.0
  #Snack Bar
  awesome_snackbar_content: ^0.1.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

  #Adaptive Dialog
  adaptive_dialog: ^2.1.0
  #Loading Indicator
  loading_indicator: ^3.1.1
  #In App Purchase
  in_app_purchase: ^3.2.0
  #Google AdMob
  google_mobile_ads: ^5.1.0
  #Glitch Affect
  animated_glitch: ^2.0.0+2
  #Neon
  neon: ^0.1.0
  #Rename
  rename: ^3.0.2
  #Kayan yazı
  flutter_infinite_marquee: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  #MOBX
  mobx_codegen: ^2.6.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.12


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/translations/
    - assets/sounds/

  fonts:
    - family: HorrorFont
      fonts:
        - asset: assets/fonts/horrorFont.ttf
          style: normal
    - family: PixelFont
      fonts:
        - asset: assets/fonts/pixel.ttf
          style: normal
    
